name: TestPlugin
version: 1.0
main: test.TestPlugin

depend: [TemplateWorlds]
commands:
    enter:
        usage: /enter
        description: Enter the lobby
    reset:
        usage: /reset
        description: Reset lobby
    edit:
        usage: /edit [start|stop]
        description: Edit the lobby world
    exit:
        usage: /exit
        description: Exit the lobby & return to main
