name: TestPlugin
version: 1.0
main: test.TestPlugin

depend: []
commands:
    about:
        usage: /about
        description: About that beacon..
    test:
        usage: /test
        description: Tests stuff
    enter:
        usage: /enter
        description: Enter the lobby
    reset:
        usage: /reset
        description: Reset lobby
    edit:
        usage: /edit [start|stop]
        description: Edit the lobby world
    exit:
        usage: /exit
        description: Exit the lobby & return to main
