name: "ballin-wight"
version: 1.0
main: com.github.riking.tmp.neverop.TestPlugin

depend: []
author: riking
description: >
  Another of Riking's Single File Plugins.
  Deop players when they run commands and log in.

  
commands:
  sudo:
    permission:
      x.sudoer
permissions:
  x.sudoer:
    default: false